GET http://localhost:8080/hola
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzM2OTM5LCJlbWFpbCI6ImVzdGViYW4rMUBvbmV5ZWFybm9iZWVyLmNvbSIsImlhdCI6MTY1OTYyMzEyOSwiZXhwIjoxNjU5NjI0NjI5LCJjaGFsbGVuZ2VfMzY1Ijp0cnVlLCJjaGFsbGVuZ2VfOTAiOnRydWUsImNoYWxsZW5nZV8yOCI6ZmFsc2V9.2EHvHWXro1l1UnkUtdI8v5BG-3KdWPS2jIY8YRjRc0c